module.exports = [
    '📝 *Escribe tu nombre completo*',
    '🎂 *¿Cuál es tu edad?*',
    '📏 *¿Cuál ha sido tu peso máximo alcanzado?* (Especifica si son kilogramos o libras)',
    '⚖️ *¿Cuál es tu peso actual?* (Especifica si son kilogramos o libras)',
    '📐 *¿Cuál es tu estatura?* (En centímetros)',
    '🕒 *Define tu rutina diaria* (Desde que te levantas hasta que te duermes)',
    '🏃‍♂️ *¿Realizas alguna actividad física?* (Responde Sí o No)',
    '⏳ *¿Cuánto tiempo llevas entrenando?* (Especifica en meses o años)',
    '🏋️‍♀️ *¿Qué tipo de entreno o actividad física realizas?*',
    '📅 *¿Cuántas veces por semana lo realizas?*',
    '🍽️ *¿Cuántas comidas realizas al día?*',
    '🍳 *¿Qué comes usualmente en el desayuno?*',
    '🥗 *¿Qué comes usualmente en el almuerzo?*',
    '🍽️ *¿Qué comes usualmente en la cena?*',
    '🍪 *Si haces snacks, especifica qué comes usualmente en ellos*',
    '🚫 *Menciona los alimentos que no consumes ya sea por alergias o por preferencia*',
    '💊 *¿Has utilizado suplementos?* (Responde Sí o No)',
    '📦 *¿Qué suplementos has utilizado?*',
    '⚕️ *¿Tienes alguna patología especial?* (Especifica)',
    '🎯 *¿Cuáles son tus objetivos?* (Pérdida de peso, ganar masa muscular, etc.)',
    '🌍 *¿En qué país resides?*'
];
